# ==== 模块信息 ==== #

__version__ = "4.9.0.3"

__author__ = "Qeggs"
__license__ = "MIT"
__copyright__ = "Copyright (c) 2025 Qeggs"
__remarks__ = "Some of the code here is generated by AI."

__github__ = [
    "https://github.com/qeggs-dev/repeater-ai-chatbot"
    "https://github.com/qeggs-dev/repeater-onebot-v11-client"
    "https://github.com/qeggs-dev/repeater-nexus"
    "https://github.com/qeggs-dev/repeater-notes-client"
    "https://github.com/qeggs-dev/auto-backup"
    "https://github.com/qeggs-dev/repeater-document-library"
    "https://github.com/qeggs-dev/repeater-model-info-server"
    "https://github.com/qeggs-dev/static-resources-server"
    "https://github.com/qeggs-dev/repeater-static-data"
    "https://github.com/qeggs-dev/repeater-render-server"
]